### ISSUE TITLE
input 'cells-lab/microvm' follows a non-existent input 'lambda-microvm-lab/microvm'

### ISSUE THREAD

**Issue by gobuki** [JuliaCN/Julia2Nix.jl#12]
Hello,

Just stumbled on this repo and was interested in trying it in a shell using `nix develop`.

That and the following
```
nix build github:JuliaCN/Julia2Nix.jl#packages.x86_64-linux.build-project
```

result in:

```
error: input 'cells-lab/microvm' follows a non-existent input 'lambda-microvm-lab/microvm'
```

I haven't investigated further. Could you share whether this input based on your other project is necessary or more for convenience?

**Comment by GTrunSec** [comment]
Could you try again? and what's your nix version?

**Comment by GTrunSec** [comment]
For the shell usage: 
```
 nix develop github:JuliaCN/Julia2Nix.jl#devShells.x86_64-linux.default
```
Aslo, you can try this command to generate the Depot.nix:

```
nix run github:JuliaCN/Julia2Nix.jl#packages.x86_64-linux.julia2nix 
```

Example: 

https://github.com/JuliaCN/Julia2Nix.jl/tree/main/templates/dev

**Comment by gobuki** [comment]
Hi, I apologize for not following up on this while it was still relevant. Thanks for your response and for building this repository.
