### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by colinxs** [JuliaCN/Julia2Nix.jl#20]
Howdy! I thought I was experiencing Deja Vu when I ran across this repo. No worries about copying [colinxs/NixSourcerer.jl](https://github.com/colinxs/NixSourcerer.jl) -- I'm glad someone's using it -- but would you mind including a brief attribution in the README and the license? Thanks!

**Comment by GTrunSec** [comment]
Thank you for your excellent work around that; added by https://github.com/JuliaCN/Julia2Nix.jl/commit/7c8156c69c775c84aa5089bae36246476b100b70.

**Comment by GTrunSec** [comment]
https://github.com/JuliaCN/Julia2Nix.jl#attribution needs your @colinxs  review.

**Comment by GTrunSec** [comment]
Sorry for not stating the attribution in the readme in the first place; I fully respect your work. https://github.com/JuliaCN/Julia2Nix.jl/pull/1

**Comment by colinxs** [comment]
Just saw this. Thank you! I'll have to check out your improved fork.

**Comment by GTrunSec** [comment]
@colinxs Since I have only been in the julia language for 2 months, I expect to get help from julia experts like you. that would be a huge help for this project and process. thanks, if you don't mind, I can invite you to be a collaborator on this project.
